### ISSUE TITLE
Check fails when PR comment edited

### ISSUE THREAD

**Issue by alex3236** [RoryQ/checkmate#13]
Log:
```
Reading Config From Inputs
Config: checkmate.Config{
    PathsChecklists: {
        "test/**": {"test1", "test2"},
    },
    Preamble: "## Test\nChecklist test",
}
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
github.com/roryq/checkmate/pkg/pullrequest.getPRNumber(...)
	/home/runner/work/checkmate/checkmate/pkg/pullrequest/client.go:93
github.com/roryq/checkmate/pkg/pullrequest.NewClient(0xc000093e90?, 0xc0000d5900)
	/home/runner/work/checkmate/checkmate/pkg/pullrequest/client.go:79 +0x30f
github.com/roryq/checkmate/pkg/checkmate.Run({0x87c7b0, 0xc000096000}, 0xc00009a738, 0xc0000a8360?, 0x7f15feee43b8?)
	/home/runner/work/checkmate/checkmate/pkg/checkmate/action.go:20 +0x86
main.run()
	/home/runner/work/checkmate/checkmate/main.go:33 +0xed
main.main()
	/home/runner/work/checkmate/checkmate/main.go:37 +0x[19]
```
Workflow:
```
on:
  pull_request:
    types: [edited, opened, reopened, synchronize]
    paths:
      - test/**
  issue_comment:

name: Checklist
jobs:
  validate-checklists:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate Checklists
        uses: roryq/checkmate@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          preamble: |
            ## Test
            Checklist test
          paths: |
            test/**:
              - test1
              - test2
```
